### PR TITLE
Created Code of Conduct

### PR DESCRIPTION
**Pull request by unrealapex**

### CODE REVIEW

**Comment by QuiteAFancyEmerald** [comment]
I mean, how is this useful lol?

**Comment by unrealapex** [comment]
I believe it would be useful because it would set some ground rules for contributors to follow, but it would probably make more sense in a repository with more than 10 contributors.

**Comment by unrealapex** [comment]
Merging it is up to you.

**Comment by QuiteAFancyEmerald** [comment]
Well, alright maybe :D
It just seems very unnecessary.

**Pull request merged**
